version: "3.8"
services:
  postgres:
    image: "postgres:15"
    container_name: "aston-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresdb
